### PR TITLE
JPMS: Add module-info to enable usage in modular projects

### PR DESCRIPTION
**Pull request by aashideacon**
I added a module-info that seems to have everything needed.

I added the javafx modules to the pom.xml, since they are no longer included in standard java.

I don't know why that surefire plugin was giving me grief..  just letting it pick its version seemed to make it go.

Also, very minor problem when doing a "mvn package" -- the javadoc was failing on that one class, I suppose due to the change in the variable name.

I saw you had an "issue" in there about updating to java 11.. The project I was using is 16, but there shouldn't be much problem going between 16 and 11, if you want to back it to 11.

Feel free to use or discard!  Hope my small effort helps.  Great project!

### CODE REVIEW

**Comment by Oliver-Loeffler** [comment]
Hi @aashideacon, thanks for the PR, yes, very cool. I will merge it over the weekend. Think beside Java 16 and JavaFX 16, its probably a good thing to have a pure Java 11 version as well (as 11 is LTS for FX and Java).

Question to you: Would you mind if I'll put the demos into a separate module/jar?

**Comment by aashideacon** [comment]
> 
Putting the demos in their own jar/module would be a good idea, so as not to have them add to other projects.

I'll test it our for you when it's done!

**Comment by Oliver-Loeffler** [comment]
Hi @aashideacon ,

please dont wonder, I'll merge the PR but will not consider the change for POM.xml yet. I welcome the module info so the next release will be modularized. `0.0.9' will be for Java-9 with modules. '0.0.10' then will be for Java 11/FX11 and there will be a version '0.0.12' for JavaFX16/Java16.

**Comment by Oliver-Loeffler** [comment]
@aashideacon Thanks for offering help with testing. I'll give you a ping once its ready to go!

**Comment by Oliver-Loeffler** [comment]
Hi @aashideacon, there are now various versions of FXFileChooser available at http://search.maven.org, ranging from Java-9 over Java-11 with OpenJFX16 to Java-17/OpenJFX17 and  even OpenJFX18/19. Please feel free to try out. Looking forward to your feedback.

**Pull request merged**
